'use server';

/**
 * @fileOverview Generates a contextual response based on the retrieved content from the selected company entity.
 *
 * - generateContextualResponse - A function that generates a contextual response.
 * - GenerateContextualResponseInput - The input type for the generateContextualResponse function.
 * - GenerateContextualResponseOutput - The return type for the generateContextualResponse function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const GenerateContextualResponseInputSchema = z.object({
  entity: z.string().describe('The company entity (Matrix, LVB, Perle, ICC SOFT, Newtelnet).'),
  query: z.string().describe('The user query.'),
  retrievedContent: z.string().describe('The content retrieved from the knowledge base for the entity.'),
});
export type GenerateContextualResponseInput = z.infer<typeof GenerateContextualResponseInputSchema>;

const GenerateContextualResponseOutputSchema = z.object({
  response: z.string().describe('The contextual and helpful response generated by the LLM.'),
});
export type GenerateContextualResponseOutput = z.infer<typeof GenerateContextualResponseOutputSchema>;

export async function generateContextualResponse(input: GenerateContextualResponseInput): Promise<GenerateContextualResponseOutput> {
  return generateContextualResponseFlow(input);
}

const prompt = ai.definePrompt({
  name: 'generateContextualResponsePrompt',
  input: {schema: GenerateContextualResponseInputSchema},
  output: {schema: GenerateContextualResponseOutputSchema},
  prompt: `You are a helpful chatbot assistant for the following company entity: {{entity}}.
  Respond to the user query based on the retrieved content from the knowledge base.
  Retrieved Content: {{retrievedContent}}
  User Query: {{query}}
  Respond in a contextual and helpful manner, avoiding generic or mixed answers. Focus on the content provided.
  Do not respond if the content is not relevant, or if you cannot generate a satisfactory answer with the provided content.
  If answering in French, ensure the response is grammatically correct and contextually appropriate for a professional setting.
  If the retrieved content is empty or irrelevant, indicate that you cannot provide an answer based on the available information.
`,
});

const generateContextualResponseFlow = ai.defineFlow(
  {
    name: 'generateContextualResponseFlow',
    inputSchema: GenerateContextualResponseInputSchema,
    outputSchema: GenerateContextualResponseOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
