import type { Entity } from './types';

export const knowledgeBase: Record<Entity, string> = {
  'Matrix Telecoms': `Matrix Telecoms S.A., filiale du Groupe ICCNET fondée en 1997, est un opérateur télécoms majeur au Cameroun spécialisé dans les services IP (Internet Protocol) pour les entreprises. Avec le slogan "Connecting People. Inspiring Solutions.", l'entreprise offre une gamme complète de services incluant la connectivité internet dédiée, les réseaux privés virtuels (VPN), la téléphonie sur IP (VoIP), et des solutions de sécurité comme la vidéosurveillance et l'hébergement en datacenter. Elle dessert les entreprises privées, publiques et les organisations internationales depuis ses bureaux à Yaoundé et Douala.`,
  'ICC SOFT': `ICCSOFT S.A., fondée en 1995, est la filiale du Groupe ICCNET spécialisée dans l'ingénierie logicielle et le développement de solutions informatiques sur mesure. Avec son slogan "Solutions Logicielles sur Mesure", elle conçoit des applications innovantes (bancaires, gestion d'entreprise, web/mobiles) pour optimiser les processus métier et la productivité. Forte d'une équipe de plus de 50 experts et de plus de 100 projets réalisés, ICCSOFT accompagne la transformation digitale des secteurs de la banque, de l'administration et de l'industrie au Cameroun et en Afrique.`,
  'New Telnet': `NEWTELNET CAMEROUN SAS, fondée en avril 2017 et opérationnelle depuis mi-2021, est un fournisseur d'accès internet (FAI) et opérateur télécoms camerounais. Avec son slogan "Unbreakable Internet Solutions", l'entreprise vise à rendre l'accès à internet fluide et permanent au Cameroun et en Afrique centrale. Ses services clés incluent la connectivité réseau (VSAT, fibre optique), la cybersécurité en partenariat avec des acteurs comme Check Point, et l'optimisation des infrastructures IT pour divers secteurs.`,
  'ADAC': `ADAC (Africa Data Center), filiale du Groupe ICCNET créée en 2017, est spécialisée dans les solutions de datacenter et de cloud computing au Cameroun. Elle est un partenaire stratégique pour les entreprises, garantissant une disponibilité de 99,98 % et une protection optimale des données. Ses services incluent des serveurs privés virtuels (VPS), la téléphonie cloud (IPBX), la vidéoconférence et la vidéosurveillance, pour soutenir la transformation digitale avec des infrastructures sécurisées et innovantes.`,
  'Groupe ICC Net': `Le Groupe ICCNET, fondé en 1995, est un conglomérat camerounais leader dans les Nouvelles Technologies de l'Information et de la Communication (NTIC). Dirigé par son PDG Clovis Tchokonte, le groupe est une plateforme de compétences intégrées avec des filiales clés comme Matrix Telecoms (le pôle télécoms majeur), ICCSOFT (développement logiciel), RESYTAL (réseaux), La Vallée de Bana (hôtellerie), et ADAC (data centers). Avec plus de 230 collaborateurs et une présence dans plus de 7 pays, sa vision est de devenir un leader de l'ingénierie informatique et des services Internet en Afrique Centrale.`,
  LVB: `La Vallée de Bana (LVB), filiale du Groupe ICCNET ouverte en 2015, est un complexe hôtelier et touristique 3 étoiles situé à Bana (Ouest Cameroun). Dans un cadre naturel et luxueux, l'établissement propose des services d'hébergement, de restauration, de bien-être (spa, piscine, sport) et d'organisation d'événements. Il incarne la diversification du groupe dans le secteur de l'écotourisme et de l'hospitalité camerounaise.`,
  Perle: `La Résidence La Perle est une destination de prestige du Groupe ICCNET, située à Bastos, Yaoundé, près de la Présidence de la République. Offrant le confort d'un hôtel 5 étoiles dans un cadre contemporain, elle dispose de 6 appartements de luxe et 15 chambres meublées. Sa mise en service a eu lieu en 2024.`,
  CCEC: `CCEC (Caisse Camerounaise d'Épargne et de Crédit S.A.), affiliée au Groupe ICCNET depuis 1996, est une institution de microfinance dédiée à la finance de proximité. Avec le slogan "La Finance de Proximité", elle soutient les PME et les entrepreneurs via des services d'épargne (y compris journalière avec MYCASH), des microcrédits, et des solutions numériques comme le mobile banking pour favoriser l'inclusion financière au Cameroun.`,
  Unknown: `Le Groupe ICC NET, avec plus de 15 années d’expérience, est le partenaire de confiance des entreprises camerounaises pour leur transformation digitale. Nous regroupons plusieurs entités spécialisées comme Matrix, ICC SOFT et Newtelnet pour offrir une gamme complète de services informatiques et télécoms.`,
};
