import type { Entity } from './types';

export const knowledgeBase: Record<Entity, string> = {
  'Matrix Telecoms': `Matrix Telecoms S.A., filiale du Groupe ICCNET fondée en 1997, est un opérateur télécoms majeur au Cameroun spécialisé dans les services IP (Internet Protocol) pour les entreprises. Avec le slogan "Connecting People. Inspiring Solutions.", l'entreprise offre une gamme complète de services incluant la connectivité internet dédiée, les réseaux privés virtuels (VPN), la téléphonie sur IP (VoIP), et des solutions de sécurité comme la vidéosurveillance et l'hébergement en datacenter. Elle dessert les entreprises privées, publiques et les organisations internationales depuis ses bureaux à Yaoundé et Douala.`,
  'ICC SOFT': `ICC-soft est la branche de développement logiciel du Groupe ICC Net. Elle est spécialisée dans la création de solutions informatiques sur mesure.
Services principaux:
- Développement de logiciels: Conception et réalisation de logiciels métiers pour optimiser les processus internes des entreprises.
- Applications Web et Mobiles: Création d'applications modernes, ergonomiques et performantes pour les plateformes web et mobiles (iOS, Android).
- Maintenance et support: Accompagnement des clients après le déploiement avec des services de maintenance évolutive et corrective.`,
  'New Telnet': `NEWTELNET CAMEROUN SAS, fournisseur d'accès internet (FAI) et opérateur camerounais, a été fondé en avril 2017 et est devenu opérationnel mi-2021. Avec son slogan "Unbreakable Internet Solutions", l'entreprise vise à rendre l'accès à internet fluide et permanent au Cameroun et en Afrique centrale. Ses services clés incluent la connectivité réseau (VSAT, fibre optique, SD-WAN), la cybersécurité en partenariat avec des acteurs comme Check Point, et l'optimisation des infrastructures IT pour divers secteurs (banque, logistique, industrie).`,
  'ADAC': `ADAC, qui signifie "Africa Datacenter", est une entité du Groupe ICC Net spécialisée dans l'hébergement d'infrastructures informatiques et les services de data center.
Services principaux:
- Colocation: Espaces sécurisés et climatisés pour héberger les serveurs des clients.
- Cloud Computing: Solutions de cloud privé et public pour une flexibilité et une scalabilité maximales.
- Sécurité et connectivité: Garantie d'une haute disponibilité et d'une sécurité physique et logique des données.`,
  'Groupe ICC Net': `Le Groupe ICCNET, fondé en 1995, est un conglomérat camerounais leader dans les Nouvelles Technologies de l'Information et de la Communication (NTIC). Dirigé par son PDG Clovis Tchokonte, le groupe compte plus de 230 collaborateurs et est présent dans plus de 7 pays africains. Sa vision est de devenir un leader en ingénierie informatique et services Internet en Afrique Centrale. Le groupe est structuré autour de plusieurs filiales autonomes, dont Matrix Telecoms (le pôle télécoms majeur), ICCSOFT (développement logiciel), RESYTAL (réseaux), La Vallée de Bana (hôtellerie), ADAC (data centers), et CCEC (microfinance).`,
  LVB: `LVB, "La Vallée de Bana", est un complexe hôtelier 3 étoiles du Groupe ICCNET, ouvert en 2015 à Bana (Ouest Cameroun). C'est une destination touristique qui allie luxe et nature, offrant des services d'hébergement, de restauration, de bien-être (spa, piscine) et d'organisation d'événements dans un cadre verdoyant. Elle incarne la diversification du groupe dans le secteur de l'écotourisme.`,
  Perle: `La Résidence La Perle est une destination de prestige du Groupe ICCNET, située à Bastos, Yaoundé, près de la Présidence de la République. Offrant le confort d'un hôtel 5 étoiles dans un cadre contemporain, elle dispose de 6 appartements de luxe et 15 chambres meublées. Sa mise en service a eu lieu en 2024.`,
  Unknown: `Le Groupe ICC NET, avec plus de 15 années d’expérience, est le partenaire de confiance des entreprises camerounaises pour leur transformation digitale. Nous regroupons plusieurs entités spécialisées comme Matrix, ICC SOFT et Newtelnet pour offrir une gamme complète de services informatiques et télécoms.`,
};
